#!/bin/bash

set -e

echo "Setting up Ruby demo..."
gem install m2x

# # Set up loadreport.rb to run every minute
# chmod 754 /vagrant/loadreport.rb
# cp /vagrant/loadreport.cron /etc/cron.d/loadreport

# # Keep loadreport.log from getting too large
# cp /vagrant/loadreport.logrotate /etc/logrotate.d/loadreport



echo "Setting up Python demo..."
VIRTUALENV_VERSION="1.11.4"
VIRTUALENV_URL="https://pypi.python.org/packages/source/v/virtualenv/"
VIRTUALENV_EXT=".tar.gz"

cd $OPENSHIFT_DATA_DIR
curl -O ${VIRTUALENV_URL}virtualenv-${VIRTUALENV_VERSION}${VIRTUALENV_EXT}
tar xvzf virtualenv-${VIRTUALENV_VERSION}${VIRTUALENV_EXT}
rm virtualenv-${VIRTUALENV_VERSION}${VIRTUALENV_EXT}
cd ${OPENSHIFT_TMP_DIR}virtualenv-${VIRTUALENV_VERSION}
python virtualenv.py ${OPENSHIFT_DATA_DIR}python-prod

source ${OPENSHIFT_DATA_DIR}python-prod/bin/activate

pip install m2x
pip install ystockquote
