#!/bin/bash

source ${OPENSHIFT_DATA_DIR}python-prod/bin/activate

export M2XKEYFILE=${OPENSHIFT_REPO_DIR}m2x_api_key.txt

python ${OPENSHIFT_REPO_DIR}stockreport.py >> ${OPENSHIFT_RUBY_LOG_DIR}stockreport.log
